#!/usr/bin/env zsh
# default config: https://github.com/koekeishiya/yabai/blob/master/examples/yabairc

# startup
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config debug_output                 on
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.2
yabai -m config insert_feedback_color        0x00ffffff
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0x33ffffff
yabai -m config normal_window_border_color   0x00ffffff

yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  24
yabai -m config bottom_padding               54
yabai -m config left_padding                 24
yabai -m config right_padding                24
yabai -m config window_gap                   24

# internal signals: all other events are handled via goku/karabiner
yabai -m signal --add event=space_changed action="~/.config/shscripts/refresh-uebersicht.sh"
yabai -m signal --add event=window_focused action="~/.config/shscripts/refresh-uebersicht.sh"
yabai -m signal --add event=application_activated action="~/.config/shscripts/refresh-uebersicht.sh"
